x-postgres-common:
  &postgres-common
  image: postgres:15.7
  restart: always
  command: |
    -c 'config_file=/etc/postgresql/postgresql.conf'
  environment:
    &postgres-common-env
    POSTGRES_USER: user
    POSTGRES_PASSWORD: 1234
    POSTGRES_DB: db
  healthcheck:
    test: [ "CMD", "pg_isready", "-U", "db" ]
    interval: 10s
    retries: 5
    start_period: 5s
  networks:
    - patroni-cluster


services:
  app:
    image: azamatkomaev/postcreator:latest
    container_name: app
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://main:5432/db
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: 1234
    depends_on:
      - main
    networks:
      - patroni-cluster

  main:
    <<: *postgres-common
    container_name: main
    ports:
      - 5432:5432
    volumes:
      - ./data/main:/var/lib/postgresql/data
      - ./data/archive:/wal-arch
      - ./config/main.conf:/etc/postgresql/postgresql.conf
      - ./config/pg_hba.conf:/etc/postgresql/pg_hba.conf

  replica1:
    ### ASYNC REPLICA
    <<: *postgres-common
    container_name: replica1
    ports:
      - 5433:5432
    volumes:
      - ./data/replica1:/var/lib/postgresql/data
      - ./config/replica1.conf:/etc/postgresql/postgresql.conf

  replica2:
    ### SYNC REPLICA
    <<: *postgres-common
    container_name: replica2
    ports:
      - 5434:5432
    volumes:
      - ./data/replica2:/var/lib/postgresql/data
      - ./config/replica2.conf:/etc/postgresql/postgresql.conf

networks:
  patroni-cluster:
