services:
  grafana:
    image: grafana/grafana-enterprise:10.1.10
    container_name: grafana
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - patroni-cluster

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    restart: always
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - '9090:9090'
    networks:
      - patroni-cluster

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0
    container_name: postgres-exporter 
    environment:
      DATA_SOURCE_URI: main:5432/db?sslmode=disable
      DATA_SOURCE_USER: user
      DATA_SOURCE_PASS: 1234
    ports:
      - '9187:9187'
    networks:
      - patroni-cluster

volumes:
  prometheus-data: {}
  grafana-data: {}

networks:
  patroni-cluster:
    external: true
    name: patroni-demo_patroni-cluster
